// JournalEntryRequest.java
package com.mymindmirror.backend.payload.request;

import lombok.Data;

/**
 * DTO for incoming journal entry creation requests from the frontend.
 */
@Data
public class JournalEntryRequest {
    private String text; // The raw journal text from the user
    // No ID or date here, as they are generated by the backend
}
